spring.application.name=aetherlia

spring.datasource.url=jdbc:mysql://localhost:3306/aetherlia
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

server.port=8081

# =====================================================
# AETHERLIA PAYMENT
# =====================================================

aetherlia.payment.bank-code=TCB
aetherlia.payment.account-number=19074384141018
aetherlia.payment.account-name=PHAM VAN TUAN
aetherlia.payment.store-name=Aetherlia

# Secret c\u1EE7a webhook SePay
aetherlia.payment.sepay-api-key=